version: '3'

services:
  spring-app:
    container_name: spring-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV}
      - JDBC_URL=${JDBC_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./logs:/app/logs